//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaExamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgendaExamen()
        {
            this.Examen_TipoExamen = new HashSet<Examen_TipoExamen>();
            this.ExamenAnulado = new HashSet<ExamenAnulado>();
        }
    
        public int Id { get; set; }
        public int fk_IdPaciente { get; set; }
        public int fk_IdFuncionarioAgendo { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaAgendada { get; set; }
        public int fk_IdSector { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> HoraRealExamen { get; set; }
        public Nullable<int> fk_IdFuncionarioAtendio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen_TipoExamen> Examen_TipoExamen { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenAnulado> ExamenAnulado { get; set; }
    }
}
