//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario_Establecimiento
    {
        public int Id { get; set; }
        public int fk_IdFuncionario { get; set; }
        public int fk_IdEstablecimiento { get; set; }
    
        public virtual Establecimiento Establecimiento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
