//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoraAnulada
    {
        public int Id { get; set; }
        public int fk_IdHoraMedica { get; set; }
        public System.DateTime FechaAnulacion { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> fk_IdRol_Persona { get; set; }
    
        public virtual HoraMedica HoraMedica { get; set; }
        public virtual Rol_Persona Rol_Persona { get; set; }
    }
}
