//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoraMedica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoraMedica()
        {
            this.HoraAnulada = new HashSet<HoraAnulada>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaHoraCargada { get; set; }
        public int fk_IdFuncionario_Especialidad { get; set; }
        public bool Disponible { get; set; }
        public Nullable<int> fk_IdPaciente { get; set; }
        public int fk_IdEstadoHoraMedica { get; set; }
        public int fk_IdSector { get; set; }
        public string Codigo { get; set; }
    
        public virtual EstadoHoraMedica EstadoHoraMedica { get; set; }
        public virtual Funcionario_Especialidad Funcionario_Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoraAnulada> HoraAnulada { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
