//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.AgendaExamen = new HashSet<AgendaExamen>();
            this.HoraMedica = new HashSet<HoraMedica>();
        }
    
        public int id { get; set; }
        public int fk_persona { get; set; }
        public Nullable<int> fk_cobertura { get; set; }
        public string Observacion { get; set; }
        public string NombresContacto { get; set; }
        public string ApellidosContacto { get; set; }
        public string ParentescoContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string CelularContacto { get; set; }
        public string EmailContacto { get; set; }
        public Nullable<int> fk_IdSector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaExamen> AgendaExamen { get; set; }
        public virtual Cobertura Cobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoraMedica> HoraMedica { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
