//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Healthcare_MS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoExamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoExamen()
        {
            this.Examen_TipoExamen = new HashSet<Examen_TipoExamen>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public int fk_IdCategoriaExamen { get; set; }
    
        public virtual CategoriaExamen CategoriaExamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen_TipoExamen> Examen_TipoExamen { get; set; }
    }
}
